<ul class="nav navbar-nav">
	<li class="active">
		<a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
    </li>

	<?php foreach($this->container as $page):?>
		<?php if(!$page->isVisible()||!$this->navigation()->accept($page)) continue; ?>
		<?php $hasChildren=$page->hasPages(); ?>
		<?php if(!$hasChildren): ?>
			<li <?php if($page->isActive()) echo 'class="active"';?> >
				<a href="<?php echo $page->getHref(); ?>">
					<?php echo $page->getLabel(); ?>
				</a>
			</li>
		<?php else:?>
			<li class "dropdown">
				<a href="#" class "dropdown-toggle" data-toggle="dropdown">				
					<?php echo $page->getLabel(); ?>
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<?php foreach($page->getPages() as $child): ?>
						<?php if(!$child->isVisible()||!$this->navigation()->accept($child)) continue;?>
						<li <?php if($child->isActive()) echo 'class="active"';?> >
							<a href="<?php echo $child->getHref(); ?>">
								<?php echo $child->getLabel(); ?>
							</a>
						</li>
					<?php endforeach;?>
				</ul>
			</li>
		<?php endif;?>
	<?php endforeach; ?>    
</ul>