<?php 

 $title = 'Edit';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'menu',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('ten'));
 echo $this->formRow($form->get('dinhTuyen'));
 echo $this->formRow($form->get('thamSo'));
 echo $this->formRow($form->get('cha'));
 echo $this->formRow($form->get('loai'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();